import { psg, type Source } from './source.ts';
import type { RollRange } from '../common.ts';

export interface Patches {
  id: string;
  name: string;
  die: string;
  results: readonly { range: RollRange; text: string }[];
  source: Source;
}

export const PATCHES = {
  id: 'patches',
  name: 'Patches',
  die: '1d100',
  results: [
    { range: [0, 0], text: '"I\'m Not A Rocket Scientist / But You\'re An Idiot"' },
    { range: [1, 1], text: 'Medic Patch (Skull and Crossbones over Cross)' },
    { range: [2, 2], text: '"Don\'t Run You\'ll Only Die Tired" Backpatch' },
    { range: [3, 3], text: 'Red Shirt Logo' },
    { range: [4, 4], text: 'Blood Type (Reference Patch)' },
    { range: [5, 5], text: '"Do I LOOK Like An Expert?"' },
    { range: [6, 6], text: 'Biohazard Symbol' },
    { range: [7, 7], text: 'Mr. Yuck' },
    { range: [8, 8], text: 'Nuclear Symbol' },
    { range: [9, 9], text: '"Eat The Rich"' },
    { range: [10, 10], text: '"Be Sure: Doubletap"' },
    { range: [11, 11], text: 'Flame Emoji' },
    { range: [12, 12], text: 'Smiley Face (Glow in the Dark)' },
    { range: [13, 13], text: '"Smile: Big Brother is Watching"' },
    { range: [14, 14], text: 'Jolly Roger' },
    { range: [15, 15], text: 'Viking Skull' },
    { range: [16, 16], text: '"APEX PREDATOR" (Sabertooth Skull)' },
    { range: [17, 17], text: 'Pin-Up Model (Ace of Spades)' },
    { range: [18, 18], text: 'Queen of Hearts' },
    { range: [19, 19], text: 'Security Guard' },
    { range: [20, 20], text: '"LONER"' },
    { range: [21, 21], text: '"Front Towards Enemy" (Claymore Mine)' },
    { range: [22, 22], text: 'Pin-Up Model (Riding Missile)' },
    { range: [23, 23], text: 'FUBAR' },
    { range: [24, 24], text: '"I\'m A (Love) Machine"' },
    { range: [25, 25], text: 'Pin-Up Model (Mechanic)' },
    { range: [26, 26], text: '"HELLO MY NAME IS:"' },
    { range: [27, 27], text: '"Powered By Coffee"' },
    { range: [28, 28], text: '"Take Me To Your Leader" (UFO)' },
    { range: [29, 29], text: '"DO YOUR JOB"' },
    { range: [30, 30], text: '"Take My Life (Please)"' },
    { range: [31, 31], text: '"Upstanding Citizen"' },
    { range: [32, 32], text: '"Allergic To Bullshit" (Medical Style Patch)' },
    { range: [33, 33], text: '"Fix Me First" (Caduceus)' },
    { range: [34, 34], text: '"I Like My Tools Clean / And My Lovers Dirty"' },
    { range: [35, 35], text: '"The Louder You Scream the Faster I Come" (Nurse Pin-Up)' },
    { range: [36, 36], text: 'HMFIC (Head Mother Fucker In Charge)' },
    { range: [37, 37], text: 'Dove in Crosshairs' },
    { range: [38, 38], text: 'Chibi Cthulhu' },
    { range: [39, 39], text: '"Welcome to the DANGER ZONE"' },
    { range: [40, 40], text: 'Skull and Crossed Wrenches' },
    { range: [41, 41], text: 'Pin-Up Model (Succubus)' },
    { range: [42, 42], text: '"DILLIGAF?"' },
    { range: [43, 43], text: '"DRINK / FIGHT / FUCK"' },
    { range: [44, 44], text: '"Work Hard / Party Harder"' },
    { range: [45, 45], text: 'Mudflap Girl' },
    { range: [46, 46], text: 'Fun Meter (reads: Bad Time)' },
    { range: [47, 47], text: '"GAME OVER" (Bride & Groom)' },
    { range: [48, 48], text: 'Heart' },
    { range: [49, 49], text: '"IMPROVE / ADAPT / OVERCOME"' },
    { range: [50, 50], text: '"SUCK IT UP"' },
    { range: [51, 51], text: '"Cowboy Up" (Crossed Revolvers)' },
    { range: [52, 52], text: '"Troubleshooter"' },
    { range: [53, 53], text: 'NASA Logo' },
    { range: [54, 54], text: 'Crossed Hammers with Wings' },
    { range: [55, 55], text: '"Keep Well Lubricated"' },
    { range: [56, 56], text: 'Soviet Hammer & Sickle' },
    { range: [57, 57], text: '"Plays Well With Others"' },
    { range: [58, 58], text: '"Live Free and Die"' },
    { range: [59, 59], text: '"IF I\'M RUNNING KEEP UP" Backpatch' },
    { range: [60, 60], text: '"Meat Bag"' },
    { range: [61, 61], text: '"I Am Not A Robot"' },
    { range: [62, 62], text: 'Red Gear' },
    { range: [63, 63], text: '"I Can\'t Fix Stupid"' },
    { range: [64, 64], text: '"Space IS My Home" (Sad Astronaut)' },
    { range: [65, 65], text: 'All Seeing Eye' },
    { range: [66, 66], text: '"Solve Et Coagula" (Baphomet)' },
    { range: [67, 67], text: '"All Out of Fucks To Give" (Astronaut with Turned Out Pockets)' },
    { range: [68, 68], text: '"Travel To Distant Places / Meet Unusual Things / Get Eaten"' },
    { range: [69, 69], text: 'BOHICA (Bend Over Here It Comes Again)' },
    { range: [70, 70], text: '"I Am My Brother\'s Keeper"' },
    { range: [71, 71], text: '"Mama Tried"' },
    { range: [72, 72], text: 'Black Widow Spider' },
    { range: [73, 73], text: '"My Other Ride Married You"' },
    { range: [74, 74], text: '"One Size Fits All" (Grenade)' },
    { range: [75, 75], text: 'Grim Reaper Backpatch' },
    { range: [76, 76], text: 'отъебись ("Fuck Off," Russian)' },
    { range: [77, 77], text: '"Smooth Operator"' },
    { range: [78, 78], text: 'Atom Symbol' },
    { range: [79, 79], text: '"For Science!"' },
    { range: [80, 80], text: '"Actually, I AM A Rocket Scientist"' },
    { range: [81, 81], text: '"Help Wanted"' },
    { range: [82, 82], text: 'Princess' },
    { range: [83, 83], text: '"NOMAD"' },
    { range: [84, 84], text: '"GOOD BOY"' },
    { range: [85, 85], text: 'Dice (Snake Eyes)' },
    { range: [86, 86], text: '"#1 Worker"' },
    { range: [87, 87], text: '"Good" (Brain)' },
    { range: [88, 88], text: '"Bad Bitch"' },
    { range: [89, 89], text: '"Too Pretty To Die"' },
    { range: [90, 90], text: '"Fuck Forever" (Roses)' },
    { range: [91, 91], text: 'Icarus' },
    { range: [92, 92], text: '"Girl\'s Best Friend" (Diamond)' },
    { range: [93, 93], text: 'Risk of Electrocution Symbol' },
    { range: [94, 94], text: 'Inverted Cross' },
    { range: [95, 95], text: '"Do You Sign My Paychecks?" Backpatch' },
    { range: [96, 96], text: '"I ♥ Myself"' },
    { range: [97, 97], text: 'Double Cherry' },
    { range: [98, 98], text: '"Volunteer"' },
    { range: [99, 99], text: "Poker Hand: Dead Man's Hand* *Aces Full Of Eights" },
  ],
  source: psg(9),
} as const satisfies Patches;
