import { psg, type Source } from './source.ts';

export type SkillTier = 'trained' | 'expert' | 'master';

export interface Skill {
  id: string;
  name: string;
  tier: SkillTier;
  bonus: 10 | 15 | 20;
  description: string | null;
  /** Skill ids; `_PREREQUISITES_RESOLVE` below is what makes them compile-checked. */
  prerequisites: readonly string[];
  /** Whether the book states the prerequisite outright, or the transcriber inferred it. */
  prerequisiteSource?: 'traced' | 'reviewed';
  source: Source;
}

export const SKILLS = [
  {
    id: 'archaeology',
    name: 'Archaeology',
    tier: 'trained',
    bonus: 10,
    description: 'Ancient cultures and artifacts.',
    prerequisites: [],
    source: psg(22, '22.2'),
  },
  {
    id: 'art',
    name: 'Art',
    tier: 'trained',
    bonus: 10,
    description: "The expression or application of a species' creative ability and imagination.",
    prerequisites: [],
    source: psg(22, '22.2'),
  },
  {
    id: 'athletics',
    name: 'Athletics',
    tier: 'trained',
    bonus: 10,
    description: 'Physical fitness, sports, and games.',
    prerequisites: [],
    source: psg(22, '22.2'),
  },
  {
    id: 'botany',
    name: 'Botany',
    tier: 'trained',
    bonus: 10,
    description: 'The study of plant life.',
    prerequisites: [],
    source: psg(22, '22.2'),
  },
  {
    id: 'chemistry',
    name: 'Chemistry',
    tier: 'trained',
    bonus: 10,
    description: 'The study of matter and its chemical elements and compounds.',
    prerequisites: [],
    source: psg(22, '22.2'),
  },
  {
    id: 'computers',
    name: 'Computers',
    tier: 'trained',
    bonus: 10,
    description: 'Fluent use of computers and their networks.',
    prerequisites: [],
    source: psg(22, '22.2'),
  },
  {
    id: 'geology',
    name: 'Geology',
    tier: 'trained',
    bonus: 10,
    description: 'The study of the solid features of any terrestrial planet or its satellites.',
    prerequisites: [],
    source: psg(22, '22.2'),
  },
  {
    id: 'industrial-equipment',
    name: 'Industrial Equipment',
    tier: 'trained',
    bonus: 10,
    description: 'The safe and proper use of heavy machinery and tools (exosuits, forklifts, drills, breakers, laser cutters, etc.).',
    prerequisites: [],
    source: psg(22, '22.2'),
  },
  {
    id: 'jury-rigging',
    name: 'Jury-Rigging',
    tier: 'trained',
    bonus: 10,
    description: 'Makeshift repair, using only the tools and materials at hand.',
    prerequisites: [],
    source: psg(22, '22.2'),
  },
  {
    id: 'linguistics',
    name: 'Linguistics',
    tier: 'trained',
    bonus: 10,
    description: 'The study of languages (alive, dead, and undiscovered).',
    prerequisites: [],
    source: psg(22, '22.2'),
  },
  {
    id: 'mathematics',
    name: 'Mathematics',
    tier: 'trained',
    bonus: 10,
    description: 'The study of numbers, quantity, and space.',
    prerequisites: [],
    source: psg(22, '22.2'),
  },
  {
    id: 'military-training',
    name: 'Military Training',
    tier: 'trained',
    bonus: 10,
    description: 'Basic training provided to all military personnel.',
    prerequisites: [],
    source: psg(22, '22.2'),
  },
  {
    id: 'rimwise',
    name: 'Rimwise',
    tier: 'trained',
    bonus: 10,
    description: 'Practical knowledge and know-how regarding outer Rim colonies, their customs, and the seedier parts of the galaxy.',
    prerequisites: [],
    source: psg(22, '22.2'),
  },
  {
    id: 'theology',
    name: 'Theology',
    tier: 'trained',
    bonus: 10,
    description: 'The study of the divine or devotion to a religion.',
    prerequisites: [],
    source: psg(22, '22.2'),
  },
  {
    id: 'zero-g',
    name: 'Zero-G',
    tier: 'trained',
    bonus: 10,
    description: 'Practice and know-how of working in a vacuum, orientation, vaccsuit operation, etc.',
    prerequisites: [],
    source: psg(22, '22.2'),
  },
  {
    id: 'zoology',
    name: 'Zoology',
    tier: 'trained',
    bonus: 10,
    description: 'The study of animal life.',
    prerequisites: [],
    source: psg(22, '22.2'),
  },
  {
    id: 'asteroid-mining',
    name: 'Asteroid Mining',
    tier: 'expert',
    bonus: 15,
    description: 'Training in the tools and procedures used for mining asteroids.',
    prerequisites: ['geology', 'industrial-equipment'],
    source: psg(23, '23.1'),
    prerequisiteSource: 'reviewed',
  },
  {
    id: 'ecology',
    name: 'Ecology',
    tier: 'expert',
    bonus: 15,
    description: 'The study of organisms and how they relate to their environment.',
    prerequisites: ['botany', 'geology'],
    source: psg(23, '23.1'),
    prerequisiteSource: 'reviewed',
  },
  {
    id: 'explosives',
    name: 'Explosives',
    tier: 'expert',
    bonus: 15,
    description: 'Design and effective use of explosive devices (bombs, grenades, shells, land mines, etc.).',
    prerequisites: ['chemistry', 'jury-rigging', 'military-training'],
    source: psg(23, '23.1'),
    prerequisiteSource: 'traced',
  },
  {
    id: 'field-medicine',
    name: 'Field Medicine',
    tier: 'expert',
    bonus: 15,
    description: 'Emergency medical care and treatment.',
    prerequisites: ['zoology'],
    source: psg(23, '23.1'),
    prerequisiteSource: 'reviewed',
  },
  {
    id: 'firearms',
    name: 'Firearms',
    tier: 'expert',
    bonus: 15,
    description: 'Safe and effective use of guns.',
    prerequisites: ['military-training', 'rimwise'],
    source: psg(23, '23.1'),
    prerequisiteSource: 'reviewed',
  },
  {
    id: 'hacking',
    name: 'Hacking',
    tier: 'expert',
    bonus: 15,
    description: 'Unauthorized access to computer systems and networks.',
    prerequisites: ['computers'],
    source: psg(23, '23.1'),
    prerequisiteSource: 'traced',
  },
  {
    id: 'hand-to-hand-combat',
    name: 'Hand-to-Hand Combat',
    tier: 'expert',
    bonus: 15,
    description: 'Melee fighting, brawling, martial arts, etc.',
    prerequisites: ['athletics', 'military-training', 'rimwise'],
    source: psg(23, '23.1'),
    prerequisiteSource: 'reviewed',
  },
  {
    id: 'mechanical-repair',
    name: 'Mechanical Repair',
    tier: 'expert',
    bonus: 15,
    description: 'Fixing broken machines.',
    prerequisites: ['industrial-equipment', 'jury-rigging'],
    source: psg(23, '23.1'),
    prerequisiteSource: 'reviewed',
  },
  {
    id: 'mysticism',
    name: 'Mysticism',
    tier: 'expert',
    bonus: 15,
    description: 'Spiritual apprehension of hidden knowledge.',
    prerequisites: ['archaeology', 'art'],
    source: psg(23, '23.1'),
    prerequisiteSource: 'traced',
  },
  {
    id: 'pathology',
    name: 'Pathology',
    tier: 'expert',
    bonus: 15,
    description: 'Study of the causes and effects of diseases.',
    prerequisites: ['zoology'],
    source: psg(23, '23.1'),
    prerequisiteSource: 'traced',
  },
  {
    id: 'pharmacology',
    name: 'Pharmacology',
    tier: 'expert',
    bonus: 15,
    description: 'Study of drugs and medication.',
    prerequisites: ['chemistry'],
    source: psg(23, '23.1'),
    prerequisiteSource: 'traced',
  },
  {
    id: 'physics',
    name: 'Physics',
    tier: 'expert',
    bonus: 15,
    description: 'Study of matter, motion, energy, and their effects in space and time.',
    prerequisites: ['mathematics'],
    source: psg(23, '23.1'),
    prerequisiteSource: 'traced',
  },
  {
    id: 'piloting',
    name: 'Piloting',
    tier: 'expert',
    bonus: 15,
    description: 'Operation and control of aircraft, spacecraft, and other vehicles.',
    prerequisites: ['zero-g'],
    source: psg(23, '23.1'),
    prerequisiteSource: 'traced',
  },
  {
    id: 'psychology',
    name: 'Psychology',
    tier: 'expert',
    bonus: 15,
    description: 'The study of behavior and the human mind.',
    prerequisites: ['linguistics', 'zoology'],
    source: psg(23, '23.1'),
    prerequisiteSource: 'reviewed',
  },
  {
    id: 'wilderness-survival',
    name: 'Wilderness Survival',
    tier: 'expert',
    bonus: 15,
    description: 'Applicable know-how regarding the basic necessities of life (food, water, shelter) in a natural environment.',
    prerequisites: ['military-training', 'theology'],
    source: psg(23, '23.1'),
    prerequisiteSource: 'reviewed',
  },
  {
    id: 'artificial-intelligence',
    name: 'Artificial Intelligence',
    tier: 'master',
    bonus: 20,
    description: 'The study of intelligence as demonstrated by machines.',
    prerequisites: ['hacking'],
    source: psg(23, '23.2'),
    prerequisiteSource: 'traced',
  },
  {
    id: 'command',
    name: 'Command',
    tier: 'master',
    bonus: 20,
    description: 'Leadership, management, and authority.',
    prerequisites: ['firearms', 'piloting'],
    source: psg(23, '23.2'),
    prerequisiteSource: 'traced',
  },
  {
    id: 'cybernetics',
    name: 'Cybernetics',
    tier: 'master',
    bonus: 20,
    description: 'The physical and neural interfaces between organisms and machines.',
    prerequisites: ['mechanical-repair'],
    source: psg(23, '23.2'),
    prerequisiteSource: 'reviewed',
  },
  {
    id: 'engineering',
    name: 'Engineering',
    tier: 'master',
    bonus: 20,
    description: 'The design, building, and use of engines, machines, and structures.',
    prerequisites: ['mechanical-repair'],
    source: psg(23, '23.2'),
    prerequisiteSource: 'traced',
  },
  {
    id: 'exobiology',
    name: 'Exobiology',
    tier: 'master',
    bonus: 20,
    description: 'The study of and search for intelligent alien life.',
    prerequisites: ['pathology'],
    source: psg(23, '23.2'),
    prerequisiteSource: 'traced',
  },
  {
    id: 'hyperspace',
    name: 'Hyperspace',
    tier: 'master',
    bonus: 20,
    description: 'Faster-than-light travel.',
    prerequisites: ['mysticism', 'physics', 'piloting'],
    source: psg(23, '23.2'),
    prerequisiteSource: 'reviewed',
  },
  {
    id: 'planetology',
    name: 'Planetology',
    tier: 'master',
    bonus: 20,
    description: 'Study of planets and other celestial bodies.',
    prerequisites: ['asteroid-mining', 'ecology'],
    source: psg(23, '23.2'),
    prerequisiteSource: 'traced',
  },
  {
    id: 'robotics',
    name: 'Robotics',
    tier: 'master',
    bonus: 20,
    description: 'Design, maintenance, and operation of robots, drones, and androids.',
    prerequisites: ['mechanical-repair'],
    source: psg(23, '23.2'),
    prerequisiteSource: 'reviewed',
  },
  {
    id: 'sophontology',
    name: 'Sophontology',
    tier: 'master',
    bonus: 20,
    description: 'The study of the behavior and mind of inhuman entities.',
    prerequisites: ['psychology'],
    source: psg(23, '23.2'),
    prerequisiteSource: 'traced',
  },
  {
    id: 'surgery',
    name: 'Surgery',
    tier: 'master',
    bonus: 20,
    description: 'Manually operating on living or dead biological subjects.',
    prerequisites: ['field-medicine', 'pathology'],
    source: psg(23, '23.2'),
    prerequisiteSource: 'reviewed',
  },
  {
    id: 'xenoesotericism',
    name: 'Xenoesotericism',
    tier: 'master',
    bonus: 20,
    description: 'Obscure beliefs, mysticism, and religion regarding non-human entities.',
    prerequisites: ['mysticism'],
    source: psg(23, '23.2'),
    prerequisiteSource: 'traced',
  },
] as const satisfies readonly Skill[];

export type SkillId = (typeof SKILLS)[number]['id'];

// Every prerequisite names a skill this catalog defines. A typo is a compile error here, which is
// the whole reason the book is TypeScript and not JSON. `Skill.prerequisites` cannot say so itself
// — `SkillId` is derived from the very array being checked.
SKILLS.flatMap((skill) => skill.prerequisites) satisfies readonly SkillId[];
