import { psg, type Source } from './source.ts';
import type { RollRange } from '../common.ts';

export interface Trinkets {
  id: string;
  name: string;
  die: string;
  results: readonly { range: RollRange; text: string }[];
  source: Source;
}

export const TRINKETS = {
  id: 'trinkets',
  name: 'Trinkets',
  die: '1d100',
  results: [
    { range: [0, 0], text: 'Manual: PANIC: Harbinger of Catastrophe' },
    { range: [1, 1], text: 'Antique Company Scrip (Asteroid Mine)' },
    { range: [2, 2], text: 'Manual: SURVIVAL: Eat Soup With a Knife' },
    { range: [3, 3], text: 'Desiccated Husk Doll' },
    { range: [4, 4], text: 'Pressed Alien Flower (common)' },
    { range: [5, 5], text: 'Necklace of Shell Casings' },
    { range: [6, 6], text: 'Corroded Android Logic Core' },
    { range: [7, 7], text: 'Pamphlet: Signs of Parasitical Infection' },
    { range: [8, 8], text: 'Manual: Treat Your Rifle Like A Lady' },
    { range: [9, 9], text: 'Bone Knife' },
    { range: [10, 10], text: 'Calendar: Alien Pin-Up Art' },
    { range: [11, 11], text: 'Rejected Application (Colony Ship)' },
    { range: [12, 12], text: 'Holographic Serpentine Dancer' },
    { range: [13, 13], text: 'Snake Whiskey' },
    { range: [14, 14], text: 'Medical Container, Purple Powder' },
    { range: [15, 15], text: 'Pills: Male Enhancement, Shoddy' },
    { range: [16, 16], text: 'Casino Playing Cards' },
    { range: [17, 17], text: 'Lagomorph Foot' },
    { range: [18, 18], text: 'Moonstone Ring' },
    { range: [19, 19], text: 'Manual: Mining Safety and You' },
    { range: [20, 20], text: 'Pamphlet: Against Human Simulacra' },
    { range: [21, 21], text: 'Animal Skull, 3 Eyes, Curled Horns' },
    { range: [22, 22], text: "Bartender's Certification (Expired)" },
    { range: [23, 23], text: 'Bunraku Puppet' },
    { range: [24, 24], text: 'Prospecting Mug, Dented' },
    { range: [25, 25], text: 'Eerie Mask' },
    { range: [26, 26], text: 'Ultrablack Marble' },
    { range: [27, 27], text: 'Ivory Dice' },
    { range: [28, 28], text: 'Tarot Cards, Worn, Pyrite Gilded Edges' },
    { range: [29, 29], text: 'Bag of Assorted Teeth' },
    { range: [30, 30], text: 'Ashes (A Relative)' },
    { range: [31, 31], text: 'DNR Beacon Necklace' },
    { range: [32, 32], text: 'Cigarettes (Grinning Skull)' },
    { range: [33, 33], text: 'Pills: Areca Nut' },
    { range: [34, 34], text: 'Pendant: Shell Fragments Suspended in Plastic' },
    { range: [35, 35], text: 'Pamphlet: Zen and the Art of Cargo Arrangement' },
    { range: [36, 36], text: 'Pair of Shot Glasses (Spent Shotgun Shells)' },
    { range: [37, 37], text: 'Key (Childhood Home)' },
    { range: [38, 38], text: 'Dog Tags (Heirloom)' },
    { range: [39, 39], text: 'Token: "Is Your Morale Improving?"' },
    { range: [40, 40], text: 'Pamphlet: The Relic of Flesh' },
    { range: [41, 41], text: 'Pamphlet: The Indifferent Stars' },
    { range: [42, 42], text: 'Calendar: Military Battles' },
    { range: [43, 43], text: 'Manual: Rich Captain, Poor Captain' },
    { range: [44, 44], text: 'Campaign Poster (Home Planet)' },
    { range: [45, 45], text: 'Preserved Insectile Aberration' },
    { range: [46, 46], text: 'Titanium Toothpick' },
    { range: [47, 47], text: 'Gloves, Leather (Xenomorph Hide)' },
    { range: [48, 48], text: 'Smut (Seditious): The Captain, Ordered' },
    { range: [49, 49], text: 'Towel, Slightly Frayed' },
    { range: [50, 50], text: 'Brass Knuckles' },
    { range: [51, 51], text: 'Fuzzy Handcuffs' },
    { range: [52, 52], text: 'Journal of Grudges' },
    { range: [53, 53], text: 'Stylized Cigarette Case' },
    { range: [54, 54], text: 'Ball of Assorted Gauge Wire' },
    { range: [55, 55], text: 'Spanner' },
    { range: [56, 56], text: 'Switchblade, Ornamental' },
    { range: [57, 57], text: 'Powdered Xenomorph Horn' },
    { range: [58, 58], text: 'Bonsai Tree, Potted' },
    { range: [59, 59], text: 'Golf Club (Putter)' },
    { range: [60, 60], text: 'Trilobite Fossil' },
    { range: [61, 61], text: 'Pamphlet: A Lover In Every Port' },
    { range: [62, 62], text: 'Patched Overalls, Personalized' },
    { range: [63, 63], text: 'Fleshy Thing Sealed in a Murky Jar' },
    { range: [64, 64], text: 'Spiked Bracelet' },
    { range: [65, 65], text: 'Harmonica' },
    { range: [66, 66], text: 'Pictorial Pornography, Dog-eared, Well-thumbed' },
    { range: [67, 67], text: 'Coffee Cup, Chipped, reads: HAPPINESS IS MANDATORY' },
    { range: [68, 68], text: 'Manual: Moonshining With Gun Oil & Fuel' },
    { range: [69, 69], text: 'Miniature Chess Set, Bone, Pieces Missing' },
    { range: [70, 70], text: 'Gyroscope, Bent, Tin' },
    { range: [71, 71], text: 'Faded Green Poker Chip' },
    { range: [72, 72], text: 'Ukulele' },
    { range: [73, 73], text: 'Spray Paint' },
    { range: [74, 74], text: 'Wanted Poster, Weathered' },
    { range: [75, 75], text: 'Locket, Hair Braid' },
    { range: [76, 76], text: 'Sculpture of a Rat (Gold)' },
    { range: [77, 77], text: 'Blanket, Fire Retardant' },
    { range: [78, 78], text: 'Hooded Parka, Fleece-Lined' },
    { range: [79, 79], text: 'BB Gun' },
    { range: [80, 80], text: 'Flint Hatchet' },
    { range: [81, 81], text: 'Pendant: Two Astronauts form a Skull' },
    { range: [82, 82], text: "Rubik's Cube" },
    { range: [83, 83], text: 'Stress Ball, reads: Zero Stress in Zero G' },
    { range: [84, 84], text: 'Sputnik Pin' },
    { range: [85, 85], text: 'Ushanka' },
    { range: [86, 86], text: 'Trucker Cap, Mesh, Grey Alien Logo' },
    { range: [87, 87], text: 'Menthol Balm' },
    { range: [88, 88], text: 'Pith Helmet' },
    { range: [89, 89], text: '10m x 10m Tarp' },
    { range: [90, 90], text: 'I Ching, Missing Sticks' },
    { range: [91, 91], text: 'Kukri' },
    { range: [92, 92], text: 'Trench Shovel' },
    { range: [93, 93], text: 'Shiv, Sharpened Butter Knife' },
    { range: [94, 94], text: 'Taxidermied Cat' },
    { range: [95, 95], text: 'Pamphlet: Interpreting Sheep Dreams' },
    { range: [96, 96], text: 'Faded Photograph, A Windswept Heath' },
    { range: [97, 97], text: 'Opera Glasses' },
    { range: [98, 98], text: 'Pamphlet: Android Overlords' },
    { range: [99, 99], text: 'Interstellar Compass, Always Points to Homeworld' },
  ],
  source: psg(8),
} as const satisfies Trinkets;
