import { psg, type Source } from './source.ts';
import type { Cost, Modifier, WoundType } from '../common.ts';

export type RangeBand = 'adjacent' | 'close' | 'long' | 'extreme';

export interface Damage {
  raw: string;
  formula: string | null;
  antiArmor: boolean;
  /** Present where the raw damage is not a bare dice formula — "1d10 per shot", and the like. */
  expression?: string;
}

export interface Weapon {
  id: string;
  name: string;
  cost: Cost;
  range: RangeBand | null;
  damage: Damage | null;
  shots: number | null;
  /** The wound tables this weapon rolls on, and with what advantage. */
  wounds: readonly { type: WoundType; modifiers: readonly Modifier[] }[];
  special: string | null;
  modifiers: readonly Modifier[];
  source: Source;
}

export const WEAPONS = [
  {
    id: 'ammo',
    name: 'Ammo',
    cost: { raw: '50cr', value: 50, each: false },
    range: null,
    damage: null,
    shots: null,
    wounds: [],
    special: 'Per magazine/container.',
    modifiers: [],
    source: psg(2),
  },
  {
    id: 'boarding-axe',
    name: 'Boarding Axe',
    cost: { raw: '150cr', value: 150, each: false },
    range: 'adjacent',
    damage: { raw: '2d10 DMG', formula: '2d10', antiArmor: false },
    shots: null,
    wounds: [{ type: 'gore-massive', modifiers: ['advantage'] }],
    special: null,
    modifiers: [],
    source: psg(2),
  },
  {
    id: 'combat-shotgun',
    name: 'Combat Shotgun',
    cost: { raw: '1,400cr', value: 1400, each: false },
    range: 'close',
    damage: { raw: '4d10 DMG', formula: '4d10', antiArmor: false },
    shots: 4,
    wounds: [{ type: 'gunshot', modifiers: [] }],
    special: '1d10 DMG at Long Range or greater.',
    modifiers: [],
    source: psg(2),
  },
  {
    id: 'crowbar',
    name: 'Crowbar',
    cost: { raw: '25cr', value: 25, each: false },
    range: 'adjacent',
    damage: { raw: '1d5 DMG', formula: '1d5', antiArmor: false },
    shots: null,
    wounds: [{ type: 'blunt-force', modifiers: ['advantage'] }],
    special: 'Grants [+] on Strength Checks to open jammed airlocks, lift heavy objects, etc.',
    modifiers: ['advantage'],
    source: psg(2),
  },
  {
    id: 'flamethrower',
    name: 'Flamethrower',
    cost: { raw: '4kcr', value: 4000, each: false },
    range: 'close',
    damage: { raw: '2d10 DMG', formula: '2d10', antiArmor: false },
    shots: 4,
    wounds: [{ type: 'fire-explosives', modifiers: ['advantage'] }],
    special: 'Body Save [-] or be set on fire (2d10 DMG / round).',
    modifiers: ['disadvantage'],
    source: psg(2),
  },
  {
    id: 'flare-gun',
    name: 'Flare Gun',
    cost: { raw: '25cr', value: 25, each: false },
    range: 'long',
    damage: { raw: '1d5 DMG', formula: '1d5', antiArmor: false },
    shots: 2,
    wounds: [{ type: 'fire-explosives', modifiers: ['disadvantage'] }],
    special: 'High intensity flare visible day and night from Long Range.',
    modifiers: [],
    source: psg(2),
  },
  {
    id: 'foam-gun',
    name: 'Foam Gun',
    cost: { raw: '500cr', value: 500, each: false },
    range: 'close',
    damage: { raw: '1 DMG', formula: null, antiArmor: false, expression: '1' },
    shots: 3,
    wounds: [{ type: 'blunt-force', modifiers: [] }],
    special: 'Body Save or become stuck. Strength Check [-] to escape.',
    modifiers: ['disadvantage'],
    source: psg(2),
  },
  {
    id: 'frag-grenade',
    name: 'Frag Grenade',
    cost: { raw: '400cr ea.', value: 400, each: true },
    range: 'close',
    damage: { raw: '3d10 DMG', formula: '3d10', antiArmor: false },
    shots: 1,
    wounds: [{ type: 'fire-explosives', modifiers: [] }],
    special: 'On a hit, damages all Adjacent to enemy.',
    modifiers: [],
    source: psg(2),
  },
  {
    id: 'general-purpose-machine-gun',
    name: 'General-Purpose Machine Gun',
    cost: { raw: '4.5kcr', value: 4500, each: false },
    range: 'long',
    damage: { raw: '4d10 DMG', formula: '4d10', antiArmor: false },
    shots: 5,
    wounds: [{ type: 'gunshot', modifiers: ['advantage'] }],
    special: 'Two-handed. Heavy. Barrel can be maneuvered to fire around corners.',
    modifiers: [],
    source: psg(2),
  },
  {
    id: 'hand-welder',
    name: 'Hand Welder',
    cost: { raw: '250cr', value: 250, each: false },
    range: 'adjacent',
    damage: { raw: '1d10 DMG', formula: '1d10', antiArmor: false },
    shots: null,
    wounds: [{ type: 'bleeding', modifiers: [] }],
    special: 'Can cut through airlock doors.',
    modifiers: [],
    source: psg(2),
  },
  {
    id: 'laser-cutter',
    name: 'Laser Cutter',
    cost: { raw: '1,200cr', value: 1200, each: false },
    range: 'long',
    damage: { raw: '1d100 DMG', formula: '1d100', antiArmor: false },
    shots: 6,
    wounds: [{ type: 'bleeding', modifiers: ['advantage'] }, { type: 'gore-massive', modifiers: ['advantage'] }],
    special: 'Two-handed. Heavy. 1 round recharge between shots.',
    modifiers: [],
    source: psg(2),
  },
  {
    id: 'nail-gun',
    name: 'Nail Gun',
    cost: { raw: '150cr', value: 150, each: false },
    range: 'close',
    damage: { raw: '1d5 DMG', formula: '1d5', antiArmor: false },
    shots: 32,
    wounds: [{ type: 'bleeding', modifiers: [] }],
    special: null,
    modifiers: [],
    source: psg(2),
  },
  {
    id: 'pulse-rifle',
    name: 'Pulse Rifle',
    cost: { raw: '2.4kcr', value: 2400, each: false },
    range: 'long',
    damage: { raw: '3d10 DMG', formula: '3d10', antiArmor: false },
    shots: 5,
    wounds: [{ type: 'gunshot', modifiers: [] }],
    special: null,
    modifiers: [],
    source: psg(2),
  },
  {
    id: 'revolver',
    name: 'Revolver',
    cost: { raw: '750cr', value: 750, each: false },
    range: 'close',
    damage: { raw: '1d10+1 DMG', formula: '1d10+1', antiArmor: false },
    shots: 6,
    wounds: [{ type: 'gunshot', modifiers: [] }],
    special: null,
    modifiers: [],
    source: psg(2),
  },
  {
    id: 'rigging-gun',
    name: 'Rigging Gun',
    cost: { raw: '350cr', value: 350, each: false },
    range: 'close',
    damage: { raw: '1d10 DMG + 2d10 DMG when removed', formula: '1d10', antiArmor: false },
    shots: 1,
    wounds: [{ type: 'bleeding', modifiers: ['advantage'] }],
    special: '100m micro-filament. Body Save or become entangled.',
    modifiers: [],
    source: psg(2),
  },
  {
    id: 'scalpel',
    name: 'Scalpel',
    cost: { raw: '50cr', value: 50, each: false },
    range: 'adjacent',
    damage: { raw: '1d5 DMG', formula: '1d5', antiArmor: false },
    shots: null,
    wounds: [{ type: 'bleeding', modifiers: ['advantage'] }],
    special: null,
    modifiers: [],
    source: psg(2),
  },
  {
    id: 'smart-rifle',
    name: 'Smart Rifle',
    cost: { raw: '5kcr', value: 5000, each: false },
    range: 'extreme',
    damage: { raw: '4d10 DMG (AA)', formula: '4d10', antiArmor: true },
    shots: 3,
    wounds: [{ type: 'gunshot', modifiers: ['advantage'] }],
    special: '[-] on Combat Check when fired at Close Range.',
    modifiers: ['disadvantage'],
    source: psg(2),
  },
  {
    id: 'smg',
    name: 'SMG',
    cost: { raw: '1kcr', value: 1000, each: false },
    range: 'long',
    damage: { raw: '2d10 DMG', formula: '2d10', antiArmor: false },
    shots: 5,
    wounds: [{ type: 'gunshot', modifiers: [] }],
    special: 'Can be fired one-handed.',
    modifiers: [],
    source: psg(2),
  },
  {
    id: 'stun-baton',
    name: 'Stun Baton',
    cost: { raw: '150cr', value: 150, each: false },
    range: 'adjacent',
    damage: { raw: '1d5 DMG', formula: '1d5', antiArmor: false },
    shots: null,
    wounds: [{ type: 'blunt-force', modifiers: [] }],
    special: 'Body Save or stunned 1 round.',
    modifiers: [],
    source: psg(2),
  },
  {
    id: 'tranq-pistol',
    name: 'Tranq Pistol',
    cost: { raw: '250cr', value: 250, each: false },
    range: 'close',
    damage: { raw: '1d5 DMG', formula: '1d5', antiArmor: false },
    shots: 6,
    wounds: [{ type: 'blunt-force', modifiers: [] }],
    special: 'If DMG dealt: enemy must Body Save or be unconscious 1d10 rounds.',
    modifiers: [],
    source: psg(2),
  },
  {
    id: 'unarmed',
    name: 'Unarmed',
    cost: { raw: 'Free', value: 0 },
    range: 'adjacent',
    damage: { raw: 'Str/10 DMG', formula: null, antiArmor: false, expression: '@str/10' },
    shots: null,
    wounds: [{ type: 'blunt-force', modifiers: [] }],
    special: null,
    modifiers: [],
    source: psg(2),
  },
  {
    id: 'vibechete',
    name: 'Vibechete',
    cost: { raw: '1kcr', value: 1000, each: false },
    range: 'adjacent',
    damage: { raw: '3d10 DMG (AA)', formula: '3d10', antiArmor: true },
    shots: null,
    wounds: [{ type: 'bleeding', modifiers: [] }, { type: 'gore-massive', modifiers: [] }],
    special: 'When dealing a Wound, roll on BOTH the Bleeding AND Gore columns.',
    modifiers: [],
    source: psg(2),
  },
] as const satisfies readonly Weapon[];

export type WeaponId = (typeof WEAPONS)[number]['id'];
